spring:
  application:
    name: runnity

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:runnity}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USER:ssafy}
    password: ${DB_PASSWORD:ssafy1234}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 60000
      connection-timeout: 30000
      pool-name: RunnityHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # ✅ 명시적으로 추가
        format_sql: false
        show_sql: false
    open-in-view: false

  data:
    redis:
      cache:
        host: ${REDIS_CACHE_HOST:localhost}
        port: ${REDIS_CACHE_PORT:6379}
      pubsub:
        host: ${REDIS_PUBSUB_HOST:localhost}
        port: ${REDIS_PUBSUB_PORT:6380}
      timeout: 2000


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: runnity-local-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

# WebSocket 설정
websocket:
  servers:
    - ${WEBSOCKET_SERVER_URL_0:wss://runnity.p-e.kr/ws/13.125.163.87}
    - ${WEBSOCKET_SERVER_URL_1:wss://runnity.p-e.kr/ws/43.203.217.82}
  ticket:
    ttl: ${WEBSOCKET_TICKET_TTL:30}
  health:
    circuit-breaker-ttl: ${WEBSOCKET_CIRCUIT_BREAKER_TTL:30}

# OAuth 설정
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    issuer: ${KAKAO_ISS:https://kauth.kakao.com}
    jwks-uri: ${KAKAO_JWKS_URI:https://kauth.kakao.com/.well-known/jwks.json}
runnity:
  redis:
    pubsub:
      host: ${REDIS_CACHE_HOST:localhost}
      port: ${REDIS_PUBSUB_PORT:6380}
      channel: runnity.pubsub

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900          # 15분
  refresh-token-expiration: 604800      # 7일

logging:
  level:
    root: INFO
    com.runnity: DEBUG

stream:
  server:
    url: ${STREAM_SERVER_URL:http://localhost:8084}